accounts/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('registration/', views.RegistrationView.as_view(), name = 'registration'),
    path('profile/', views.ProfileView.as_view(), name = 'profile'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/settings/', views.ProfileSettingsView.as_view(), name='settings'),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name = 'password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name = 'password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url = reverse_lazy('accounts:password_reset_done')), name = 'password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name = 'password_reset_done'),
    path('password-reset/<uid64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name = 'password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name = 'password_reset_complete')
]

favourites/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'favourites'

urlpatterns = [
    path('list/', login_required(views.ClientFavouritesView.as_view()), name='list'),
    path('add/<str:master_name>', login_required(views.AddFavouriteView.as_view()), name='add'),
    path('remove/<str:master_name>', login_required(views.RemoveFavouriteView.as_view()), name='remove')
]

mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.MainView.as_view(), name = 'main')
]

service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('mainpage.urls')),
    path('services/', include('services.urls')),
    path('masters/', include('masters.urls')),
    path('appointments/', include('appointments.urls')),
    path('favourites/', include('favourites.urls')),
    path('visits/', include('visits.urls'))
]

services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [
    path('list/', views.ServicesView.as_view(), name='list')
]

visits/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'visits'

urlpatterns = [
    path('list/', login_required(views.VisitsView.as_view()), name='list'),
    path('<int:id>/', login_required(views.VisitDetailView.as_view()), name='detail'),
]

templates/includes/header.html
{% load bootstrap5 %}
{% load custom_tags %}

<nav class = 'navbar'>
  <ul class = 'nav navbar'>
    {% with request.resolver_match.view_name as view_name %}
      <li class = 'nav-item'>
        <a href = "{% url 'mainpage:main' %}" class = 'btn-up{% if view_name == "mainpage:main" %} btn-active{% endif %}'>Главная</a>
      </li>
      <li class = 'nav-item'>
        <a href = "{% url 'services:list' %}" class = 'btn-up{% if view_name == "services:list" %} btn-active{% endif %}'>Услуги</a>
      </li>
      {% if user.is_authenticated %}
      <li class = 'nav-item'>
        <a href = "{% url 'accounts:profile' %}" class = 'btn-up{% if view_name == "accounts:profile" %} btn-active{% endif %}'>
          {{ user }}
        </a>
      </li>
      <li class = 'nav-item'>
        <a href = '{% url "appointments:list" %}' class = 'btn-up{% if view_name == "appointments:list" %} btn-active{% endif %}'>Мои записи</a>
      </li>
      <li class = 'nav-item'>
        <a href = '{% url "visits:list" %}' class = 'btn-up{% if view_name == "visits:list" %} btn-active{% endif %}'>Мои посещения</a>
      </li>
      <li class = 'nav-item'>
        <a href = "{% url 'favourites:list' %}" class = 'btn-up{% if view_name == "favourites:list" %} btn-active{% endif %}'>Избранное</a>
      </li>
      <li class = 'nav-item'>
        <form action = "{% url 'accounts:logout' %}" method = 'post'>
          {% csrf_token %}
          {% button_submit 'Выйти' 'btn-border' %}
        </form>
      </li>
      {% else %}
      <li class = 'nav-item'>
        <a href = "{% url 'accounts:login' %}" class = 'btn-border'>Войти</a>
      </li>
      <li class = 'nav-item'>
        <a href = "{% url 'accounts:registration' %}" class = 'btn-border'>Регистрация</a>
      </li>
      {% endif %}
      <li class = 'nav-item'>
        <text class = 'fs-1'>Массажный салон <i>"М@сс@ж"</i></text>
      </li>
      {% endwith %}
  </ul>
</nav>