favourites/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'favourites'

urlpatterns = [
    path('list/', login_required(views.ClientFavouritesView.as_view()), name='list'),
    path('add/<str:master_name>', login_required(views.AddFavouriteView.as_view()), name='add'),
    path('remove/<str:master_name>', login_required(views.RemoveFavouriteView.as_view()), name='remove')
]

service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('mainpage.urls')),
    path('services/', include('services.urls')),
    path('masters/', include('masters.urls')),
    path('appointments/', include('appointments.urls')),
    path('favourites/', include('favourites.urls')),
    path('visits/', include('visits.urls'))
]

visits/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'visits'

urlpatterns = [
    path('list/', login_required(views.VisitsView.as_view()), name='list'),
    path('<int:id>/', login_required(views.VisitDetailView.as_view()), name='detail'),
]

visits/models.py
from django.db import models
from accounts.models import custom_user_foreign_key
from masters.models import Master
from services.models import Service

# Create your models here.

class Visit(models.Model):
    id = models.AutoField(primary_key=True)
    client = models.ForeignKey(
        custom_user_foreign_key(),
        on_delete=models.CASCADE,
        verbose_name='Клиент'
    )
    master = models.ForeignKey(
        Master,
        on_delete=models.CASCADE,
        verbose_name='Парикмахер'
    )
    start_time = models.DateTimeField(
        verbose_name='Дата и время начала'
    )
    end_time = models.DateTimeField(
        verbose_name='Дата и время окончания'
    )
    all_price = models.DecimalField(
        verbose_name='Стоимость',
        max_digits=6,
        decimal_places=2,
    )
    services = models.ManyToManyField(
        Service,
        verbose_name='Оказанные услуги'
    )

    def __str__(self) -> str:
        return f'{self.client} - {self.master}: {self.start_time.strftime('%d %m %Y / %H:%M')} - {self.end_time.strftime('%d %m %Y / %H:%M')}'
    
    class Meta:
        verbose_name='Посещение'
        verbose_name_plural='Посещения'

visits/views.py
from typing import Any
from django.shortcuts import get_object_or_404
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.views.generic import ListView, DetailView
from .models import Visit
from accounts.models import custom_user
from favourites.models import ClientFavourites

# Create your views here.

class VisitsView(ListView):
    model = Visit
    template_name='visits/list.html'

    def get_queryset(self) -> QuerySet[Any]:
        return Visit.objects.filter(client = custom_user(self.request))

class VisitDetailView(DetailView):
    model = Visit
    template_name='visits/detail.html'

    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
        return get_object_or_404(Visit, client = custom_user(self.request), id = self.kwargs['id'])
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = {}
        context['object'] = kwargs['object']
        fav = ClientFavourites.objects.filter(client = custom_user(self.request))
        if fav:
            context['is_favourite'] = True if context['object'].master in fav[0].masters.all() else False
        else:
            context['is_favourite'] = False
        return context

templates/visits/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}{{ object }}{% endblock %}

{% block content %}
<h1>Посещение</h1>
{% info_tag 'Массажист' object.master %}
{% info_tag 'Общая стоимость, Р' object.all_price %}
{% info_tag 'Дата и время начала' object.start_time|format:'%d %m %Y / %H:%M' %}
{% info_tag 'Дата и время завершения' object.end_time|format:'%d %m %Y / %H:%M' %}
{% if not is_favourite %}
<form method="post" action="{% url 'favourites:add' object.master.name %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    {% button_submit 'Добавить парикмахера в избранное' 'btn-light-shadow' %}
</form>
{% endif %}
<h2>Выбранные услуги</h2>
{% table %}
    {% thead 'Название' 'Цена, Р' 'Описание' %}
    <tbody>
        {% for service in object.services.all %}
        {% tr service.name service.price service.description %}
        {% endfor %}
    </tbody>
{% endtable %}
{% endblock %}

templates/visits/list.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}Мои посещения{% endblock %}

{% block content %}
<h1>Посещения</h1>
{% table %}
    {% thead 'Массажист' 'Стоимость, Р' 'Время и дата начала' 'Время и дата конца' '' %}
    <tbody>
        {% for visit in object_list %}
        {% tr %}
            {% td visit.master %}
            {% td visit.all_price %}
            {% td visit.start_time|format:'%d %m %Y / %H:%M' %}
            {% td visit.end_time|format:'%d %m %Y / %H:%M' %}
            {% td %}
                <a href="{% url 'visits:detail' visit.id %}" class="btn-press">Подробнее</a>
            {% endtd %}
        {% endtr %}
        {% empty %}
            {% error_tag 'У вас пока нет посещений' %}
        {% endfor %}
    </tbody>
{% endtable %}
{% endblock %}