appointments/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'appointments'

urlpatterns = [
    path('new/select_master/', login_required(views.SelectMasterView.as_view()), name='select_master'),
    path('new/select_master/<str:name>/', login_required(views.SelectedMaster.as_view()), name='selected_master'),
    path('new/select_services/', login_required(views.SelectServicesView.as_view()), name='select_services'),
    path('new/select_services/add/<str:name>/',login_required( views.AddedService.as_view()), name='add_service'),
    path('new/select_services/remove/<str:name>/', login_required(views.RemovedService.as_view()), name='remove_service'),
    path('new/select_date/', login_required(views.SelectDateView.as_view()), name='select_date'),
    path('new/select_date/<str:date>/', login_required(views.SelectedDate.as_view()), name='selected_date'),
    path('new/select_time/', login_required(views.SelectTimeView.as_view()), name='select_time'),
    path('new/success/<int:id>/', login_required(views.SuccessView.as_view()), name='success'),
    path('new/error/', login_required(views.ErrorView.as_view()), name='error'),
    path('new/select_time/<str:time>/', login_required(views.SelectedTime.as_view()), name='selected_time'),
    path('list/', login_required(views.AppointmentsView.as_view()), name='list'),
    path('<int:id>/', login_required(views.AppointmentDetailView.as_view()), name='detail'),
    path('<int:id>/confirm/', login_required(views.AppointmentConfirmView.as_view()), name='confirm'),
    path('confirmed/', login_required(views.AppointmentConfirmedView.as_view()), name='confirmed'),
    path('<int:id>/cancel/', login_required(views.AppointmentCancelView.as_view()), name='cancel'),
    path('canceled/', login_required(views.AppointmentCanceledView.as_view()), name='canceled'),
]

service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('mainpage.urls')),
    path('services/', include('services.urls')),
    path('masters/', include('masters.urls')),
    path('appointments/', include('appointments.urls')),
    path('favourites/', include('favourites.urls')),
    path('visits/', include('visits.urls'))
]

visits/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'visits'

urlpatterns = [
    path('list/', login_required(views.VisitsView.as_view()), name='list'),
    path('<int:id>/', login_required(views.VisitDetailView.as_view()), name='detail'),
]

appointments/models.py
from django.db import models
from accounts.models import custom_user_foreign_key
from masters.models import Master, MasterTime
from services.models import Service
from datetime import datetime
# Create your models here.

class Appointment(models.Model):
    id = models.AutoField(primary_key=True)
    client = models.ForeignKey(
        custom_user_foreign_key(),
        on_delete = models.CASCADE,
        verbose_name='Клиент'
    )
    master = models.ForeignKey(
        Master,
        on_delete = models.CASCADE,
        verbose_name='Массажист'
    )
    start_time = models.DateTimeField(
        verbose_name='Дата и время начала'
    )
    services = models.ManyToManyField(
        Service,
        verbose_name='Услуги'
    )

    class Meta:
        verbose_name='Запись'
        verbose_name_plural = 'Записи'
    
    def __str__(self):
        return f'{self.client} - {self.master}: {self.start_time.strftime('%d %m %Y / %H:%M')}'

    def get_all_price(self):
        return sum(i.price for i in self.services.all())
    
    def get_all_duration(self):
        return sum(i.time for i in MasterTime.objects.filter(service__in = self.services.all(), master = self.master))
    
    def get_services_with_duration(self):
        return MasterTime.objects.filter(service__in = self.services.all(), master = self.master)
    
    def can_be_confirmed(self):
        return self.start_time.replace(tzinfo=None) <= datetime.now()

appointments/views.py
from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.http import HttpRequest
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, RedirectView, TemplateView, DetailView
from masters.models import Master, MasterTime
from .appointment import OAppointment
from services.models import Service
from favourites.models import ClientFavourites
from accounts.models import custom_user
from django.urls import reverse
from working_schedule.models import get_free_time
from datetime import timedelta, datetime
from appointments.models import Appointment
from visits.models import Visit

# Create your views here.

class SelectMasterView(ListView):
    template_name = 'appointment/select_master.html'
    model = Master

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = {}
        context['object_list'] = Master.objects.filter(is_works = True)
        cf = ClientFavourites.objects.filter(client = custom_user(self.request))
        context['favourites'] = cf[0].masters.all() if cf else []
        return context

class SelectedMaster(RedirectView):
    http_method_names = ['post']

    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
        return reverse('appointments:select_services')
    
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        appointment = OAppointment(request)
        appointment.set_master(get_object_or_404(Master, name = kwargs['name']))
        return super().post(request, *args, **kwargs)

class AddedService(RedirectView):
    http_method_names = ['post']

    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
        return reverse('appointments:select_services')
    
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        appointment = OAppointment(request)
        appointment.add_service(get_object_or_404(Service, name = kwargs['name']))
        return super().post(request, *args, **kwargs)

class RemovedService(RedirectView):
    http_method_names = ['post']

    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
        return reverse('appointments:select_services')
    
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        appointment = OAppointment(request)
        appointment.remove_service(get_object_or_404(Service, name = kwargs['name']))
        return super().post(request, *args, **kwargs)

class SelectServicesView(ListView):
    template_name = 'appointment/select_services.html'
    model = MasterTime

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = {}
        appointment = OAppointment(self.request)
        context['object_list'] = MasterTime.objects.filter(master = appointment.get_master())
        context['appointment'] = appointment
        return context
    
class SelectDateView(TemplateView):
    template_name = 'appointment/select_date.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = {}
        context['dates'] = []
        appointment = OAppointment(self.request)
        context['appointment'] = appointment
        for i in range(0, 15):
            if get_free_time(datetime.now() + timedelta(days=i), appointment.get_all_duration()):
                context.get('dates').append((datetime.now() + timedelta(days=i)).date())
        return context

class SelectedDate(RedirectView):
    http_method_names=['post']

    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
        return reverse('appointments:select_time')
    
    def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        appointment = OAppointment(self.request)
        appointment.set_date(kwargs['date'])
        return super().post(request, *args, **kwargs)

class SelectTimeView(TemplateView):
    template_name = 'appointment/select_time.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = {}
        appointment = OAppointment(self.request)
        context['appointment'] = appointment
        context['times'] = get_free_time(appointment.get_date(), appointment.get_all_duration())
        return context

class SelectedTime(RedirectView):
    http_method_names=['post']

    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
        appointment = OAppointment(self.request)
        appointment.set_time(kwargs['time'])
        ap = appointment.create_appointment(custom_user(self.request))
        if ap:
            return reverse('appointments:success', kwargs={'id': ap.id})
        else:
            return reverse('appointments:error')

class SuccessView(DetailView):
    template_name = 'appointment/success.html'
    model = Appointment
    
    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
        return get_object_or_404(Appointment, id = self.kwargs['id'])

class ErrorView(TemplateView):
    template_name = 'appointment/error.html'

class AppointmentsView(ListView):
    model = Appointment
    template_name = 'appointment/list.html'

    def get_queryset(self) -> QuerySet[Any]:
        return Appointment.objects.filter(client = custom_user(self.request))

class AppointmentDetailView(DetailView):
    template_name='appointment/detail.html'
    model = Appointment

    def get_object(self, queryset: QuerySet[Any] | None = ...) -> Model:
        return get_object_or_404(Appointment, id = self.kwargs['id'])

class AppointmentConfirmedView(TemplateView):
    template_name='appointment/confirmed.html'

class AppointmentConfirmView(RedirectView):
    http_method_names=['post']

    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
        appointment = get_object_or_404(Appointment, id = kwargs['id'])
        new_visit = Visit(
            client = appointment.client,
            master = appointment.master,
            start_time = appointment.start_time,
            end_time = appointment.start_time + timedelta(minutes=appointment.get_all_duration()),
            all_price = appointment.get_all_price()
        )
        new_visit.save()
        new_visit.services.set(appointment.services.all())
        new_visit.save()
        appointment.delete()
        return reverse('appointments:confirmed')

class AppointmentCanceledView(TemplateView):
    template_name='appointment/canceled.html'

class AppointmentCancelView(RedirectView):
    http_method_names=['post']
    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
        get_object_or_404(Appointment, id = kwargs['id']).delete()
        return reverse('appointments:canceled')

templates/appointment/canceled.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}Запись отменена{% endblock %}

{% block content %}
<h1>Запись успешно отменена</h1>
{% endblock %}

templates/appointment/confirmed.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}Запись потверждена{% endblock %}

{% block content %}
<h1>Запись успешно потверждена</h1>
{% endblock %}

templates/appointment/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}{{ object }}{% endblock %}

{% block content %}
<br>
{% info_tag 'Массажист' object.master %}
{% info_tag 'Общая продолжительность, мин' object.get_all_duration %}
{% info_tag 'Общая стоимость, Р' object.get_all_price %}
{% info_tag 'Дата и время' object.start_time|format:'%d %m %Y / %H:%M' %}
<h2>Выбранные услуги</h2>
{% table %}
    {% thead 'Название' 'Цена, Р' 'Продолжительность, мин' 'Описание' %}
    <tbody>
        {% for i in object.get_services_with_duration %}
        {% tr i.service.name i.service.price i.time i.service.description %}
        {% endfor %}
    </tbody>
{% endtable %}
<form method="post" action="{% url 'appointments:cancel' object.id %}">
    {% csrf_token %}
    {% button_submit 'Отменить' 'btn-light-shadow' %}
</form>
{% if object.can_be_confirmed %}
<form method="post" action="{% url 'appointments:confirm' object.id %}">
    {% csrf_token %}
    {% button_submit 'Потвердить' 'btn-light-shadow' %}
</form>
{% endif %}
{% endblock %}

templates/appointment/error.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}Ошибка записи{% endblock %}

{% block content %}
<h1>К сожалению во время создания записи произошбла ошибка</h1>
<h2>Среди возможных причин, вы не заполнили информацию или такое время уже занято</h2>
{% endblock %}

templates/appointment/list.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}Мои записи{% endblock %}

{% block content %}
<h1>Записи</h1>
{% table %}
    {% thead 'Массажист' 'Стоимость, Р' 'Продолжительность, мин' 'Время и дата' '' %}
    <tbody>
        {% for appointment in object_list %}
        {% tr %}
            {% td appointment.master %}
            {% td appointment.get_all_price %}
            {% td appointment.get_all_duration %}
            {% td appointment.start_time|format:'%d %m %Y / %H:%M' %}
            {% td %}
                <a href="{% url 'appointments:detail' appointment.id %}" class="btn-press">Подробнее</a>
            {% endtd %}
        {% endtr %}
        {% empty %}
            {% error_tag 'У вас пока нет записей' %}
        {% endfor %}
    </tbody>
{% endtable %}
{% endblock %}

templates/appointment/select_date.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}Выбор даты{% endblock %}

{% block content %}
<h1>Выберите дату</h1>
<a href="{% url 'appointments:select_services' %}" class="btn-light-shadow">Назад</a>
<br><br>
{% info_tag 'Массажист' appointment.get_master %}
{% info_tag 'Общая продолжительность, мин' appointment.get_all_duration %}
{% info_tag 'Общая стоимость, Р' appointment.get_all_price %}
<h2>Выбранные услуги</h2>
{% table %}
    {% thead 'Название' 'Цена, Р' 'Продолжительность, мин' 'Описание' %}
    <tbody>
        {% for i in appointment.get_services_with_duration %}
        {% tr i.service.name i.service.price i.time i.service.description %}
        {% endfor %}
    </tbody>
{% endtable %}
{% stack %}
    {% for date in dates %}
        {% stack_el %}
        <form method = 'post' action = "{% url 'appointments:selected_date' date %}">
            {% csrf_token %}
            <input type = 'submit' value = '{{ date }}' class = 'btn-press'>
        </form>
        {% endstack_el %}
    {% endfor %}
{% endstack %}
{% endblock %}

templates/appointment/select_master.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}Выбор массажиста{% endblock %}

{% block content %}
<h1>Выберите массажиста</h1>
{% table %}
    {% thead 'ФИО' 'В избранном' '' %}
    <tbody>
        {% for master in object_list %}
            {% tr %}
                {% td master %}
                {% if master in favourites %}
                    {% td 'Да' %}
                {% else %}
                    {% td 'Нет' %}
                {% endif %}
                {% td %}
                    <form method="post" action="{% url 'appointments:selected_master' master.name %}">
                        {% csrf_token %}
                        {% button_submit 'Выбрать' 'btn-press' %}
                    </form>
                {% endtd %}
            {% endtr %}
        {% empty %}
        {% error_tag 'К сожалению, на данный момент нет доступных парикмахеров' %}
        {% endfor %}
    </tbody>
{% endtable %}
{% endblock %}

templates/appointment/select_services.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}Выбор услуг{% endblock %}

{% block content %}
<h1>Выберите услуги</h1>
<a href="{% url 'appointments:select_master' %}" class="btn-light-shadow">Назад</a>
<br><br>
{% info_tag 'Массажист' appointment.get_master %}
{% info_tag 'Общая продолжительность, мин' appointment.get_all_duration %}
{% info_tag 'Общая стоимость, Р' appointment.get_all_price %}
{% table %}
    {% thead 'Название' 'Цена, Р' 'Продолжительность, мин' 'Описание' '' %}
    <tbody>
        {% for master_time in object_list %}
        {% tr %}
            {% td master_time.service.name %}
            {% td master_time.service.price %}
            {% td master_time.time %}
            {% td master_time.service.description %}
            {% td %}
                {% if master_time.service in appointment.get_services %}
                <form method="post" action="{% url 'appointments:remove_service' master_time.service.name %}">
                    {% csrf_token %}
                    {% button_submit 'Удалить' 'btn-press' %}
                </form>
                {% else %}
                <form method="post" action="{% url 'appointments:add_service' master_time.service.name %}">
                    {% csrf_token %}
                    {% button_submit 'Добавить' 'btn-press' %}
                </form>
                {% endif %}
            {% endtd %}
        {% endtr %}
        {% endfor %}
    </tbody>
{% endtable %}
{% if appointment.get_services %}
<a href="{% url 'appointments:select_date' %}" class="btn-light-shadow">Выбрать дату</a>
{% endif %}
{% endblock %}

templates/appointment/select_time.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}Выбор времени{% endblock %}

{% block content %}
<h1>Выберите время</h1>
<a href="{% url 'appointments:select_date' %}" class="btn-light-shadow">Назад</a>
<br><br>
{% info_tag 'Массажист' appointment.get_master %}
{% info_tag 'Общая продолжительность, мин' appointment.get_all_duration %}
{% info_tag 'Общая стоимость, Р' appointment.get_all_price %}
{% info_tag 'Дата' appointment.get_date|format:'%d %m %Y' %}
<h2>Выбранные услуги</h2>
{% table %}
    {% thead 'Название' 'Цена, Р' 'Продолжительность, мин' 'Описание' %}
    <tbody>
        {% for i in appointment.get_services_with_duration %}
        {% tr i.service.name i.service.price i.time i.service.description %}
        {% endfor %}
    </tbody>
{% endtable %}
{% stack %}
    {% for time in times %}
        {% stack_el %}
        <form method = 'post' action = "{% url 'appointments:selected_time' time %}">
            {% csrf_token %}
            <input type = 'submit' value = '{{ time }}' class = 'btn-press'>
        </form>
        {% endstack_el %}
    {% endfor %}
{% endstack %}
{% endblock %}

templates/appointment/success.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load custom_tags %}

{% block title %}Запись создана{% endblock %}

{% block content %}
<h1>Запись успешно создана</h1>
{% info_tag 'Массажист' object.master %}
{% info_tag 'Общая продолжительность, мин' object.get_all_duration %}
{% info_tag 'Общая стоимость, Р' object.get_all_price %}
{% info_tag 'Дата и время' object.start_time|format:'%d %m %Y / %H:%M' %}
<h2>Выбранные услуги</h2>
{% table %}
    {% thead 'Название' 'Цена, Р' 'Продолжительность, мин' 'Описание' %}
    <tbody>
        {% for i in object.get_services_with_duration %}
        {% tr i.service.name i.service.price i.time i.service.description %}
        {% endfor %}
    </tbody>
{% endtable %}
{% endblock %}